### ISSUE TITLE
What are the issues that you are facing with circle ci?

### ISSUE THREAD

**Issue by yedhink** [rishabhanand12/granite#1]
@rishabhanand12 _a

Let me know what exactly are the issues that you are facing with circleci.

**Comment by yedhink** [comment]
@rishabhanand12 

I just noticed this. You are using ruby version 2.7.2 but your circle ci config uses 2.7.1

Please update it to 2.7.2 and see if the issues persist in circleci.

**Comment by rishabhanand12** [comment]
@yedhink 

I bumped ruby version from 2.7.1 to 2.7.2. This corrected the previous error. However there is another error that I have come across another error. It says error loading 'postgresql' while trying to setup the database. 
I believe the command that led to this error is 
bundle exec rake db:create db:schema:load --trace

**Comment by yedhink** [comment]
@rishabhanand12 

That is because you have used postgresql in your ci database config:
https://github.com/rishabhanand12/granite/blob/7b97cdc90897591f4598c88183b38ed1803b61a3/config/database.yml.ci#L2


Currently we haven't updated that chapter in the book. But we will be doing that in the next phase of revamp. But till then i think you can modify and use the below mentioned config.

You can add the following or something similar in your `database.yml.ci`:
```yaml
# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  <<: *default
  database: granite_test<%= ENV['CIRCLE_NODE_INDEX'] %>

production:
  <<: *default
  database: db/production.sqlite3
```

Maybe you might have to set `CIRCLE_NODE_INDEX` in circleci settings in their UI. Please update over here what happens when you use above config.
